# Generated by Django 5.0.6 on 2025-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_test_remove_orderitem_menu_item_remove_order_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_available", models.BooleanField(default=True)),
                ("is_special_today", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Test",
        ),
    ]
