# Generated by Django 5.0.6 on 2025-07-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_menuitem_delete_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.BooleanField(
                        choices=[
                            ("pending", "Pending"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("items", models.ManyToManyField(to="orders.menuitem")),
            ],
        ),
    ]
